# Reference: https://github.com/apps/settings
repository:
    name: banyan-core

    default_branch: main
    private: true

    description: Banyan Computer's internal platform services
    homepage: https://banyan.computer/
    topics: api, platform

    has_issues: false
    has_projects: false
    has_wiki: false
    has_downloads: false

    allow_squash_on_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false

    enable_automated_security_fixes: true
    enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      enforce_admins: true

      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
        require_code_owner_reviews: true

      required_status_checks:
        strict: true
        contexts:
          - "rust"
          - "node"

      # Required to to be present due too a limitation in GitHub's GraphQL API
      restrictions: null
      required_linear_history: true

teams:
  # High level change management is controlled by members in this authorized group
  - name: change-management-owners
    permission: admin
  # There are some devops related files in this repo, allow them to make changes
  - name: devops
    permission: push
  # Main developers of this repository
  - name: internal-engineers
    permission: push
  # Allow external contractors we've allowed to push to this repo
  - name: external-contractors
    permission: push
