# Reference: https://github.com/apps/settings
repository:
    name: banyan-core

    default_branch: main
    private: true

    description: Banyan Computer's internal platform services
    homepage: https://banyan.computer/
    topics: api, platform

    has_issues: false
    has_projects: false
    has_wiki: false
    has_downloads: false

    allow_squash_on_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false

    enable_automated_security_fixes: true
    enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      enforce_admins: true

      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
        require_code_owner_reviews: true

      required_status_checks:
        strict: true
        contexts:
          # NOTE to best understand this, configure the steps in the web UI, then hit the API REST endpoint to see how
          #      these are realized by GitHub, URL to curl is https://api.github.com/repos/banyancomputer/banyan-core/branches/main
          #      in short, it strips the `ci` prefix for some reason but everything else is the same as the names that
          #      show up in the GitHub Actions web UI when it runs
          # rust steps
          - "rust / audit"
          - "rust / build"
          - "rust / format"
          - "rust / test"
          # node banyan-core-service/admin_frontend steps
          - "node (banyan-core-service, admin_frontend) / audit"
          - "node (banyan-core-service, admin_frontend) / build"
          - "node (banyan-core-service, admin_frontend) / test"
          # node banyan-core-service/frontend steps
          - "node (banyan-core-service, frontend) / audit"
          - "node (banyan-core-service, frontend) / build"
          - "node (banyan-core-service, frontend) / test"
          # node banyan-storage-provider-service/frontend steps
          - "node (banyan-storage-provider-service, frontend) / audit"
          - "node (banyan-storage-provider-service, frontend) / build"
          - "node (banyan-storage-provider-service, frontend) / test"

      # Required to to be present due too a limitation in GitHub's GraphQL API
      restrictions: null
      required_linear_history: true

teams:
  # High level change management is controlled by members in this authorized group
  - name: change-management-owners
    permission: admin
  # There are some devops related files in this repo, allow them to make changes
  - name: devops
    permission: push
  # Main developers of this repository
  - name: internal-engineers
    permission: push
  # Allow external contractors we've allowed to push to this repo
  - name: external-contractors
    permission: push
