# This file configures `cargo deny` for validating that dependencies are secure
# (do not have security advisories), exclusively using licenses that we allow,
# and are not in our banned crates list.
#
# It is worth calling out that `cargo deny` only looks at metadata of packages,
# `cargo audit` performs the same security advisory checks but performs deep
# scans on the content of the code as well to provide additional detections on
# whether a vulnerability is present. The two tools should be used together.

# Collect metadata using all the features available in this repository. We do
# not want security vulnerabilities in any of our subset of builds.
all-features = true

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"

# If we accept an advisory either because no fix is available and we need to
# continue development, or because a vulnerability doesn't effect how we use
# the other crate their identifier should be added to this list. It should be
# periodically reviewed and cleaned out as fixes become available.
ignore = [
    # Our dependencies are locked on this particular version so we are unable
    # to update to a non-vulnerable version. That being said we're also not
    # impacted by this vulnerability as the impacted code is converting between
    # local timezones from offsets and we only operate on UTC timestamps.
    "RUSTSEC-2020-0071",
]

[licenses]
unlicensed = "deny"

# Licenses we always allow without any additional thoughts, this list should
# only be updated when we encounter a dependency using a license we want to
# include here rather than trying to proactively enumerate all acceptable
# licenses.
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "OpenSSL",
  "Unicode-DFS-2016",
]

# We don't care what these organization think of the license, we are making our
# own assessments as to whether they are fit for our project.
allow-osi-fsf-free = "neither"

# Licenses that we have reviewed and chosen to explicitly reject.
deny = []

# If a license is considered copyleft, we want to consider them carefully as
# they may violate our license or goals by their use. Copy left licenses should
# be reviewed and selectively added by the lead maintainer only.
copyleft = "deny"

# If we haven't approved it, explicitly deny it
default = "deny"

# If we need to use a crate that violates our general policy, we can add that
# to the list here to accept it.
exceptions = [
    { name = "banyan-api-client", allow = ["LicenseRef-LICENSE.txt"] },
    { name = "banyan-core-service", allow = ["LicenseRef-LICENSE.txt"] },
    { name = "banyan-staging-service", allow = ["LicenseRef-LICENSE.txt"] },
    { name = "banyan-storage-provider-service", allow = ["LicenseRef-LICENSE.txt"] },
]

# Ring doesn't specify the license in their Cargo manifest, we have to
# specifically tell cargo-deny what it is.
[[licenses.clarify]]
name = "ring"
expression = "OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "deny"
wildcards = "deny"

# Crates/versions that are always allowed regardless of which checks they trigger
allow = [
  #{ name = "ansi_term", version = "=0.11.0" },
]

# Crates and versions that are explicitly denied from use in this project
deny = []

# Certain crates/versions that will be skipped when doing duplicate detection.
# They just couldn't be resolved ourselves.
skip = [
    { name = "base64", version = "0.13.1" },    # headers v0.3.8

    { name = "bitflags", version = "1.3.1" },   # several dependencies
    { name = "bitflags", version = "2.3.2" },   # tower-http 0.4.1

    { name = "hashbrown", version = "0.12.3" }, # indexmap v1.9.3
    { name = "hashbrown", version = "0.14.0" }, # several dependencies

    { name = "idna", version = "0.3.0" },   # validify v1.0.11
    { name = "idna", version = "0.4.0" },   # url v2.4.0

    { name = "indexmap", version = "1.9.3" },   # several dependencies
    { name = "indexmap", version = "2.0.0" },   # several dependencies

    { name = "pem", version = "1.1.1" },  # jsonwebtoken v8.3.0
    { name = "pem", version = "2.0.1" },  # us

    { name = "regex-automata", version = "0.1.10" },    # matchers v0.1.0
    { name = "regex-automata", version = "0.3.1" },     # several dependencies

    { name = "regex-syntax", version = "0.6.29" },      # several dependencies
    { name = "regex-syntax", version = "0.7.2" },       # regex v1.8.4

    { name = "spin", version = "0.5.2" },  # several dependencies
    { name = "spin", version = "0.9.8" },  # several dependencies

    { name = "syn", version = "1.0.109" },  # several dependencies
    { name = "syn", version = "2.0.23" },   # several dependencies

    { name = "time", version = "0.1.45" },  # chrono v0.4.26
    { name = "time", version = "0.3.22" },  # several dependencies

    { name = "wasi", version = "0.10.0+wasi-snapshot-preview1" },   # time v0.1.45
    { name = "wasi", version = "0.11.0+wasi-snapshot-preview1" }    # several dependencies
]

[sources]
# We do not allow registries other than the official crates one which is known
# by default.
unknown-registry = "deny"

# Using a git repository as a crate source is denied by default, to use a git
# repo as a dependency source they must be reviewed and approved for use by the
# lead project maintainer (who will approve the modifications to this file as
# required by the CODEOWNERS file).
unknown-git = "deny"

# Crates that have been approved by the lead maintainer to use a git source
allow-git = []
