/**
 * Device API Key
 * Key material for verifying signatures from a given device
 * @property id - the id of the device api key (generated by the database)
 * @property accountId - the id of the account that owns the device api key
 * @property fingerprint - the fingerprint of the device's public ecdsa key -- compressed point EC public key fingerprint.
 * @property pem - the device's public ecdsa key in PEM format
 */
export interface DeviceApiKey {
    id: string;
    accountId: string;
    fingerprint: string;
    pem: string;
}
