/**
 * @interface EscrowedDevice - A user's escrowed device key material Banyan Services.
 * Primary key material for the user's account.
 * Should be generated locally on account creation. Escrowed to our Auth Service.
 * @property id - the id of the device api key (generated by the database)
 * @property accountId - the id of the account that owns the device api key
 * @property apiKeyfingerprint - the fingerprint of the device's public ecdsa key -- compressed point EC public key fingerprint.
 * @property encryptionKeyPem - the pem formatted ecdh public encryption key for the user's account
 * @property wrappedApiKey - the wrapped private ecdsa key - generated using webCrytpo.subtle.wrapKey with pkcs8 format and exporint as base64
 * @property wrappedEncryptionKey - the wrapped private ecdh key - generated using webCrytpo.subtle.wrapKey with pkcs8 format and exporint as base64
 * @property passKeySalt - the salt used to derive the user's pass key, when used in conjunction with the user's pass key.
 */
export interface EscrowedDevice {
	id: string;
	accountId: string;
	apiKeyPem: string;
	encryptionKeyPem: string;
	wrappedApiKey: string;
	wrappedEncryptionKey: string;
	passKeySalt: string;
}
