[package]
name = "banyan-core-service"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-LICENSE.txt"

[dependencies]
anyhow = "^1"
chrono = { version = "0.4.26", features = ["serde"] }
rand = "^0.8"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
uuid = { version = "^1.3", features = ["fast-rng", "serde", "v4"] }

tokio = { version = "^1", features = ["macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"] }

axum = { version = "^0.6", features = ["headers", "http2", "tracing"] }
http = "^0.2"
jsonwebtoken = "^8.3"
tower = { version = "^0.4", features = ["timeout", "load-shed", "limit", "util"] }
tower-http = { version = "^0.4", features = ["auth", "cors", "limit", "fs", "propagate-header", "request-id", "sensitive-headers", "set-header", "util", "trace", "validate-request"] }
validify = "^1.0"

tracing = "^0.1"
tracing-appender = "^0.2"
tracing-futures = { version = "^0.2", default-features = false, features = ["std-future"] }
tracing-subscriber = { version = "^0.3", default-features = false, features = ["ansi", "env-filter", "fmt", "local-time", "time", "tracing"] }

[dev-dependencies]
proptest = "^1.1"
