classDiagram
direction BT
class background_tasks {
   text original_task_id
   text task_name
   text queue_name
   text unique_key
   text state
   integer current_attempt
   integer maximum_attempts
   blob payload
   blob error
   timestamp scheduled_at
   timestamp scheduled_to_run_at
   timestamp started_at
   timestamp finished_at
   text id
}
class block_locations {
   text metadata_id
   text block_id
   text storage_host_id
   timestamp associated_at
   timestamp expired_at
   timestamp pruned_at
}
class blocks {
   varchar(64) cid
   timestamp created_at
   text id
}
class bucket_keys {
   text bucket_id
   text pem
   text fingerprint
   boolean approved
   text id
}
class buckets {
   text user_id
   varchar(128) name
   varchar(32) type
   varchar(32) storage_class
   text id
}
class deals {
   text state
   text accepted_by
   timestamp accepted_at
   timestamp created_at
   timestamp updated_at
   text id
}
class device_api_keys {
   text user_id
   varchar(50) fingerprint
   text pem
   timestamp created_at
   timestamp updated_at
   text id
}
class email_stats {
   text user_id
   integer sent
   integer accepted
   integer delivered
   integer opened
   integer complained
   integer unsubscribed
   integer rejected
   integer failed
   text id
}
class emails {
   text user_id
   timestamp sent_at
   text type
   varchar(32) state
   text id
}
class escrowed_devices {
   text user_id
   text api_public_key_pem
   text encryption_public_key_pem
   text encrypted_private_key_material
   text pass_key_salt
   timestamp created_at
   text id
}
class metadata {
   text bucket_id
   text root_cid
   text metadata_cid
   integer expected_data_size
   integer data_size
   integer metadata_size
   text metadata_hash
   text state
   timestamp created_at
   timestamp updated_at
   text id
}
class oauth_provider_accounts {
   text user_id
   text provider
   text provider_id
   timestamp associated_at
   text id
}
class oauth_state {
   text provider
   text csrf_secret
   text pkce_verifier_secret
   text next_url
   timestamp created_at
}
class sessions {
   text user_id
   text provider
   text client_ip
   text user_agent
   text access_token
   timestamp access_expires_at
   text refresh_token
   timestamp created_at
   timestamp expires_at
   text id
}
class snapshot_block_locations {
   text snapshot_id
   text block_id
}
class snapshot_restore_requests {
   text user_id
   text snapshot_id
   text storage_host_id
   text state
   timestamp created_at
   timestamp completed_at
   text id
}
class snapshot_segment_associations {
   text snapshot_id
   text segment_id
}
class snapshot_segments {
   text deal_id
   integer size
   timestamp created_at
   timestamp updated_at
   text id
}
class snapshots {
   text metadata_id
   text state
   integer size
   timestamp created_at
   text id
}
class snapshots_storage_hosts {
   text snapshot_id
   text storage_host_id
   timestamp assigned_at
   timestamp due_by
   varchar(32) status
   timestamp finalized_at
   text id
}
class sqlite_master {
   text type
   text name
   text tbl_name
   int rootpage
   text sql
}
class storage_grants {
   text storage_host_id
   text user_id
   integer authorized_amount
   timestamp created_at
   timestamp redeemed_at
   text id
}
class storage_hosts {
   varchar(128) name
   text url
   integer used_storage
   integer available_storage
   varchar(50) fingerprint
   text pem
   text id
}
class storage_hosts_metadatas_storage_grants {
   text storage_host_id
   text metadata_id
   text storage_grant_id
}
class users {
   text email
   boolean verified_email
   text display_name
   text locale
   text profile_image
   timestamp created_at
   timestamp accepted_tos_at
   text id
}

background_tasks  -->  background_tasks : original_task_id:id
block_locations  -->  blocks : block_id:id
block_locations  -->  metadata : metadata_id:id
block_locations  -->  storage_hosts : storage_host_id:id
bucket_keys  -->  buckets : bucket_id:id
buckets  -->  users : user_id:id
deals  -->  storage_hosts : accepted_by:id
device_api_keys  -->  users : user_id:id
email_stats  -->  users : user_id:id
emails  -->  users : user_id:id
escrowed_devices  -->  users : user_id:id
metadata  -->  buckets : bucket_id:id
oauth_provider_accounts  -->  users : user_id:id
sessions  -->  users : user_id:id
snapshot_block_locations  -->  blocks : block_id:id
snapshot_block_locations  -->  snapshots : snapshot_id:id
snapshot_restore_requests  -->  snapshots : snapshot_id:id
snapshot_restore_requests  -->  storage_hosts : storage_host_id:id
snapshot_restore_requests  -->  users : user_id:id
snapshot_segment_associations  -->  snapshot_segments : segment_id:id
snapshot_segment_associations  -->  snapshots : snapshot_id:id
snapshot_segments  -->  deals : deal_id:id
snapshots  -->  metadata : metadata_id:id
snapshots_storage_hosts  -->  snapshots : snapshot_id:id
snapshots_storage_hosts  -->  storage_hosts : storage_host_id:id
storage_grants  -->  storage_hosts : storage_host_id:id
storage_grants  -->  users : user_id:id
storage_hosts_metadatas_storage_grants  -->  metadata : metadata_id:id
storage_hosts_metadatas_storage_grants  -->  storage_grants : storage_grant_id:id
storage_hosts_metadatas_storage_grants  -->  storage_hosts : storage_host_id:id
