version: '3.8'
services:
  # Our Web service
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DB_PATH: /app/db.sqlite
    env_file:
      - .env.dev

volumes:
  db:
    driver: local
