/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBucketConfiguration {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "replicas", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub replicas: Option<Option<i64>>,
}

impl ApiBucketConfiguration {
    pub fn new() -> ApiBucketConfiguration {
        ApiBucketConfiguration {
            name: None,
            replicas: None,
        }
    }
}

