/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBucketKey {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "bucket_id")]
    pub bucket_id: String,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "pem")]
    pub pem: String,
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
}

impl ApiBucketKey {
    pub fn new(id: String, bucket_id: String, approved: bool, pem: String, fingerprint: String) -> ApiBucketKey {
        ApiBucketKey {
            id,
            bucket_id,
            approved,
            pem,
            fingerprint,
        }
    }
}

