/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiEscrowedKeyMaterial {
    #[serde(rename = "api_public_key_pem")]
    pub api_public_key_pem: String,
    #[serde(rename = "encryption_public_key_pem")]
    pub encryption_public_key_pem: String,
    #[serde(rename = "encrypted_private_key_material")]
    pub encrypted_private_key_material: String,
    #[serde(rename = "pass_key_salt")]
    pub pass_key_salt: String,
}

impl ApiEscrowedKeyMaterial {
    pub fn new(api_public_key_pem: String, encryption_public_key_pem: String, encrypted_private_key_material: String, pass_key_salt: String) -> ApiEscrowedKeyMaterial {
        ApiEscrowedKeyMaterial {
            api_public_key_pem,
            encryption_public_key_pem,
            encrypted_private_key_material,
            pass_key_salt,
        }
    }
}

