/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBucketKeyResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
}

impl ApiBucketKeyResponse {
    pub fn new(id: String, approved: bool, fingerprint: String) -> ApiBucketKeyResponse {
        ApiBucketKeyResponse {
            id,
            approved,
            fingerprint,
        }
    }
}

