/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiInvoice {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "billing_start")]
    pub billing_start: String,
    #[serde(rename = "billing_end")]
    pub billing_end: String,
    #[serde(rename = "subscription_id")]
    pub subscription_id: String,
    #[serde(rename = "total_amount")]
    pub total_amount: i64,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl ApiInvoice {
    pub fn new(id: String, billing_start: String, billing_end: String, subscription_id: String, total_amount: i64, status: String, created_at: String) -> ApiInvoice {
        ApiInvoice {
            id,
            billing_start,
            billing_end,
            subscription_id,
            total_amount,
            status,
            created_at,
        }
    }
}

