/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiMetadataResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "state")]
    pub state: models::MetadataState,
    #[serde(rename = "storage_host")]
    pub storage_host: String,
    #[serde(rename = "storage_authorization", skip_serializing_if = "Option::is_none")]
    pub storage_authorization: Option<String>,
}

impl ApiMetadataResponse {
    pub fn new(id: String, state: models::MetadataState, storage_host: String) -> ApiMetadataResponse {
        ApiMetadataResponse {
            id,
            state,
            storage_host,
            storage_authorization: None,
        }
    }
}

