/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizationGrant {
    #[serde(rename = "authorization_token")]
    pub authorization_token: String,
}

impl AuthorizationGrant {
    pub fn new(authorization_token: String) -> AuthorizationGrant {
        AuthorizationGrant {
            authorization_token,
        }
    }
}

