/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketUsage {
    #[serde(rename = "size")]
    pub size: f64,
}

impl BucketUsage {
    pub fn new(size: f64) -> BucketUsage {
        BucketUsage {
            size,
        }
    }
}

