/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// BucketType : The type of the bucket
/// The type of the bucket
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BucketType {
    #[serde(rename = "backup")]
    Backup,
    #[serde(rename = "interactive")]
    Interactive,

}

impl ToString for BucketType {
    fn to_string(&self) -> String {
        match self {
            Self::Backup => String::from("backup"),
            Self::Interactive => String::from("interactive"),
        }
    }
}

impl Default for BucketType {
    fn default() -> BucketType {
        Self::Backup
    }
}

