/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBucketRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: models::BucketType,
    #[serde(rename = "storage_class")]
    pub storage_class: models::StorageClass,
    #[serde(rename = "initial_bucket_key_pem")]
    pub initial_bucket_key_pem: String,
}

impl CreateBucketRequest {
    pub fn new(name: String, r#type: models::BucketType, storage_class: models::StorageClass, initial_bucket_key_pem: String) -> CreateBucketRequest {
        CreateBucketRequest {
            name,
            r#type,
            storage_class,
            initial_bucket_key_pem,
        }
    }
}

