/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBucketKeyRequest {
    /// The PEM encoded public key for the device
    #[serde(rename = "pem")]
    pub pem: String,
}

impl CreateBucketKeyRequest {
    pub fn new(pem: String) -> CreateBucketKeyRequest {
        CreateBucketKeyRequest {
            pem,
        }
    }
}

