/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceApiKey {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
}

impl DeviceApiKey {
    pub fn new(id: String, user_id: String, fingerprint: String) -> DeviceApiKey {
        DeviceApiKey {
            id,
            user_id,
            fingerprint,
        }
    }
}

