/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManageSubscription200Response {
    #[serde(rename = "portal_url", skip_serializing_if = "Option::is_none")]
    pub portal_url: Option<String>,
}

impl ManageSubscription200Response {
    pub fn new() -> ManageSubscription200Response {
        ManageSubscription200Response {
            portal_url: None,
        }
    }
}

