/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderGrantResponse {
    #[serde(rename = "token")]
    pub token: String,
}

impl ProviderGrantResponse {
    pub fn new(token: String) -> ProviderGrantResponse {
        ProviderGrantResponse {
            token,
        }
    }
}

