/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurchaseSubscription200Response {
    #[serde(rename = "checkout_url", skip_serializing_if = "Option::is_none")]
    pub checkout_url: Option<String>,
}

impl PurchaseSubscription200Response {
    pub fn new() -> PurchaseSubscription200Response {
        PurchaseSubscription200Response {
            checkout_url: None,
        }
    }
}

