/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestoreSnapshot200Response {
    /// The ID of the restore request
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl RestoreSnapshot200Response {
    pub fn new() -> RestoreSnapshot200Response {
        RestoreSnapshot200Response {
            id: None,
        }
    }
}

