/*
 * Banyan Core Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// StorageClass : The storage class of the bucket
/// The storage class of the bucket
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StorageClass {
    #[serde(rename = "hot")]
    Hot,
    #[serde(rename = "warm")]
    Warm,
    #[serde(rename = "cold")]
    Cold,

}

impl ToString for StorageClass {
    fn to_string(&self) -> String {
        match self {
            Self::Hot => String::from("hot"),
            Self::Warm => String::from("warm"),
            Self::Cold => String::from("cold"),
        }
    }
}

impl Default for StorageClass {
    fn default() -> StorageClass {
        Self::Hot
    }
}

