name: 💕 Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    tags:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: cargo build --workspace --bins --tests --benches
      - name: test
        run: cargo test --workspace --bins --tests --benches

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: add rustfmt
        run: rustup component add rustfmt
      - name: add clippy
        run: rustup component add clippy
      - name: format
        run: cargo fmt --all -- --check
      - name: lint
        run: cargo clippy --workspace --all-targets --all-features --tests -- -D warnings
