---
name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
    with:
      cache_version: v1
      # FIXME remove audit ignores
      #       RUSTSEC-2023-007: rsa crate, side-channel timing attack, no fix as of 2024-03-20
      cargo_audit_ignores: RUSTSEC-2023-0071

  node:
    uses: ./.github/workflows/node.yml
    strategy:
      fail-fast: false
      matrix:
        job:
          - service: banyan-core-service
            frontend: admin_frontend
          - service: banyan-core-service
            frontend: frontend
          - service: banyan-storage-provider-service
            frontend: frontend
    with:
      cache_version: v1
      service: ${{ matrix.job.service }}
      frontend: ${{ matrix.job.frontend }}

  # Needs to be split out so it doesn't run on every push to PRs
  #docker:
  #  uses: ./.github/workflows/docker.yml
  #  # rust and node testing/auditing must pass before producing a docker image
  #  needs:
  #    - rust
  #    - node
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      service:
  #        - banyan-core-service
  #        - banyan-staging-service
  #        - banyan-storage-provider-service
  #  with:
  #    service: ${{ matrix.service }}
