name: 🔍 Continuous Integration
on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --examples

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --all-features --tests -- -D warnings

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Nightly is needed for code coverage collection
          toolchain: nightly
          override: true
      # Swatinem/rust-cache@v2 is useful for nightly builds, so just use very basic caching
      - uses: actions/cache@v3
        name: Set up cargo cache for nightly tests
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-rust-nightly-tests-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-rust-nightly-tests-

      - uses: actions-rs/cargo@v1
        name: Run all workspace tests
        with:
          command: test
          #args: --workspace --lib --bins --tests --benches
          args: --workspace --bins --tests --benches
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"

      # No library targets in this repo
      #- uses: actions-rs/cargo@v1
      #  name: Run all doc tests
      #  with:
      #    command: test
      #    args: --workspace --doc
      #  env:
      #    CARGO_INCREMENTAL: 0
      #    RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"

      - uses: actions-rs/grcov@v0.1
        id: coverage
