name: 💕 Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    tags:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: cargo build --workspace --bins --tests --benches
      - name: test
        run: make test

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: format
        run: make fmt-check
      - name: lint
        run: make clippy
