name: 🔧 Infrastructure Security Audits
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'k8s/**'

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/tfsec-action@v1.0.0
