name: 🔧 Infrastructure Security Audits
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'k8s/**'

jobs:
  terrascan-docker:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: tenable/terrascan-action@main
      with:
        iac_type: "docker"
        verbose: true
 
  #terrascan-k8s:
  #  runs-on: ubuntu-22.04

  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: tenable/terrascan-action@main
  #    with:
  #      iac_type: "k8s"
  #      verbose: true
 
  #terrascan-kustomize:
  #  runs-on: ubuntu-22.04

  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: tenable/terrascan-action@main
  #    with:
  #      iac_type: "kustomize"
  #      verbose: true
